name: layout-drupal-example
recipe: drupal8
config:
  webroot: web
  drush: 9
  php: '7.2'
tooling:
  drush:
    service: appserver
    cmd: "drush --root=/app/web --uri=https://layout-drupal-example.lndo.site"
