<?php return unserialize('O:8:"stdClass":6:{s:3:"cid";s:72:"toolbar:[languages:language_interface]=en:[theme]=thunder_admin:[user]=1";s:4:"data";a:3:{s:7:"#markup";O:25:"Drupal\\Core\\Render\\Markup":1:{s:9:"' . "\0" . '*' . "\0" . 'string";s:6271:"

<!-- THEME DEBUG -->
<!-- THEME HOOK: \'toolbar\' -->
<!-- BEGIN OUTPUT from \'core/themes/classy/templates/navigation/toolbar.html.twig\' -->
<div id="toolbar-administration" role="group" aria-label="Site administration toolbar" class="toolbar">
  <nav id="toolbar-bar" role="navigation" aria-label="Toolbar items" class="toolbar-bar clearfix">
    <h2 class="visually-hidden">Toolbar items</h2>
                <div class="home-toolbar-tab toolbar-tab">
        <a href="/" title="Return to site content" class="toolbar-icon toolbar-icon-escape-admin toolbar-item" data-toolbar-escape-admin>Back to site</a>
        <div><nav class="toolbar-lining clearfix" role="navigation"></nav></div>      </div>
                <div class="toolbar-tab">
        <a href="/admin" title="Admin menu" class="toolbar-icon toolbar-icon-menu trigger toolbar-item" data-drupal-subtrees="" id="toolbar-item-administration" data-toolbar-tray="toolbar-item-administration-tray" role="button" aria-pressed="false">Manage</a>
        <div id="toolbar-item-administration-tray" data-toolbar-tray="toolbar-item-administration-tray" class="toolbar-tray"><nav class="toolbar-lining clearfix" role="navigation" aria-label="Administration menu"><h3 class="toolbar-tray-name visually-hidden">Administration menu</h3><!-- THEME DEBUG --><!-- THEME HOOK: \'container\' --><!-- BEGIN OUTPUT from \'themes/contrib/thunder_admin/templates/form/container.html.twig\' --><div class="toolbar-menu-administration"><!-- THEME DEBUG --><!-- THEME HOOK: \'menu__toolbar__admin\' --><!-- FILE NAME SUGGESTIONS:
   * menu--toolbar--admin.html.twig
   x menu--toolbar.html.twig
   x menu--toolbar.html.twig
   * menu.html.twig
--><!-- BEGIN OUTPUT from \'core/themes/stable/templates/navigation/menu--toolbar.html.twig\' --><ul class="toolbar-menu"><li class="menu-item"><a href="/admin/content" title="Find and manage content." id="toolbar-link-system-admin_content" class="toolbar-icon toolbar-icon-system-admin-content" data-drupal-link-system-path="admin/content">Content</a></li><li class="menu-item menu-item--collapsed"><a href="/admin/structure" title="Administer blocks, content types, menus, etc." id="toolbar-link-system-admin_structure" class="toolbar-icon toolbar-icon-system-admin-structure" data-drupal-link-system-path="admin/structure">Structure</a></li><li class="menu-item"><a href="/admin/appearance" title="Select and configure themes." id="toolbar-link-system-themes_page" class="toolbar-icon toolbar-icon-system-themes-page" data-drupal-link-system-path="admin/appearance">Appearance</a></li><li class="menu-item"><a href="/admin/modules" title="Add and enable modules to extend site functionality." id="toolbar-link-system-modules_list" class="toolbar-icon toolbar-icon-system-modules-list" data-drupal-link-system-path="admin/modules">Extend</a></li><li class="menu-item menu-item--collapsed"><a href="/admin/config" title="Administer settings." id="toolbar-link-system-admin_config" class="toolbar-icon toolbar-icon-system-admin-config" data-drupal-link-system-path="admin/config">Configuration</a></li><li class="menu-item"><a href="/admin/people" title="Manage user accounts, roles, and permissions." id="toolbar-link-entity-user-collection" class="toolbar-icon toolbar-icon-entity-user-collection" data-drupal-link-system-path="admin/people">People</a></li><li class="menu-item menu-item--collapsed"><a href="/admin/reports" title="View reports, updates, and errors." id="toolbar-link-system-admin_reports" class="toolbar-icon toolbar-icon-system-admin-reports" data-drupal-link-system-path="admin/reports">Reports</a></li></ul><!-- END OUTPUT from \'core/themes/stable/templates/navigation/menu--toolbar.html.twig\' --></div><!-- END OUTPUT from \'themes/contrib/thunder_admin/templates/form/container.html.twig\' --></nav></div>      </div>
                <div class="toolbar-tab">
        <a href="/admin/config/user-interface/shortcut" title="Shortcuts" class="toolbar-icon toolbar-icon-shortcut trigger toolbar-item" id="toolbar-item-shortcuts" data-toolbar-tray="toolbar-item-shortcuts-tray" role="button" aria-pressed="false">Shortcuts</a>
        <div id="toolbar-item-shortcuts-tray" data-toolbar-tray="toolbar-item-shortcuts-tray" class="toolbar-tray"><nav class="toolbar-lining clearfix" role="navigation" aria-label="User-defined shortcuts"><h3 class="toolbar-tray-name visually-hidden">User-defined shortcuts</h3><!-- THEME DEBUG --><!-- THEME HOOK: \'links__toolbar_shortcuts\' --><!-- FILE NAME SUGGESTIONS:
   * links--toolbar-shortcuts.html.twig
   x links.html.twig
--><!-- BEGIN OUTPUT from \'core/themes/classy/templates/navigation/links.html.twig\' --><ul class="toolbar-menu"><li><a href="/node/add">Add content</a></li><li><a href="/admin/content">All content</a></li></ul><!-- END OUTPUT from \'core/themes/classy/templates/navigation/links.html.twig\' --><a href="/admin/config/user-interface/shortcut/manage/default/customize" class="edit-shortcuts">Edit shortcuts</a></nav></div>      </div>
                <div class="hidden contextual-toolbar-tab toolbar-tab">
        <button class="toolbar-icon toolbar-icon-edit toolbar-item" aria-pressed="false" type="button">Edit</button>

        <div><nav class="toolbar-lining clearfix" role="navigation"></nav></div>      </div>
                <div class="toolbar-tab">
        <a href="/user" title="My account" class="toolbar-icon toolbar-icon-user trigger toolbar-item" id="toolbar-item-user" data-toolbar-tray="toolbar-item-user-tray" role="button" aria-pressed="false"><drupal-render-placeholder callback="user.toolbar_link_builder:renderDisplayName" arguments="" token="-MH2NzEnTzbzMk0ZGfGgoiw7G3j_-Q1ILWBRVhIOKLI"></drupal-render-placeholder></a>
        <div id="toolbar-item-user-tray" data-toolbar-tray="toolbar-item-user-tray" class="toolbar-tray"><nav class="toolbar-lining clearfix" role="navigation" aria-label="User account actions"><h3 class="toolbar-tray-name visually-hidden">User account actions</h3><drupal-render-placeholder callback="user.toolbar_link_builder:renderToolbarLinks" arguments="" token="xssKdKFVFD7N0FUPPcC1C7LrqMHpQFVzUhrI4cOeEgs"></drupal-render-placeholder></nav></div>      </div>
      </nav>
  
</div>

<!-- END OUTPUT from \'core/themes/classy/templates/navigation/toolbar.html.twig\' -->

";}s:9:"#attached";a:3:{s:7:"library";a:5:{i:0;s:15:"toolbar/toolbar";i:1;s:22:"user/drupal.user.icons";i:2;s:36:"contextual/drupal.contextual-toolbar";i:3;s:24:"shortcut/drupal.shortcut";i:4;s:27:"toolbar/toolbar.escapeAdmin";}s:12:"placeholders";a:2:{s:176:"<drupal-render-placeholder callback="user.toolbar_link_builder:renderToolbarLinks" arguments="" token="xssKdKFVFD7N0FUPPcC1C7LrqMHpQFVzUhrI4cOeEgs"></drupal-render-placeholder>";a:1:{s:13:"#lazy_builder";a:2:{i:0;s:44:"user.toolbar_link_builder:renderToolbarLinks";i:1;a:0:{}}}s:175:"<drupal-render-placeholder callback="user.toolbar_link_builder:renderDisplayName" arguments="" token="-MH2NzEnTzbzMk0ZGfGgoiw7G3j_-Q1ILWBRVhIOKLI"></drupal-render-placeholder>";a:1:{s:13:"#lazy_builder";a:2:{i:0;s:43:"user.toolbar_link_builder:renderDisplayName";i:1;a:0:{}}}}s:14:"drupalSettings";a:1:{s:7:"toolbar";a:2:{s:11:"breakpoints";a:3:{s:14:"toolbar.narrow";s:35:"only screen and (min-width: 16.5em)";s:16:"toolbar.standard";s:37:"only screen and (min-width: 38.125em)";s:12:"toolbar.wide";s:33:"only screen and (min-width: 61em)";}s:12:"subtreesHash";s:43:"redJ1BLTsYtHQL9dECc0PeM-VpwLGQEue_ppgIhz8_U";}}}s:6:"#cache";a:3:{s:8:"contexts";a:5:{i:0;s:28:"languages:language_interface";i:1;s:5:"theme";i:2;s:4:"user";i:3;s:16:"user.permissions";i:4;s:20:"user.roles:anonymous";}s:4:"tags";a:5:{i:0;s:27:"config:shortcut.set.default";i:1;s:24:"config:system.menu.admin";i:2;s:30:"config:user.role.administrator";i:3;s:30:"config:user.role.authenticated";i:4;s:6:"user:1";}s:7:"max-age";i:-1;}}s:7:"created";d:1580835562.897;s:6:"expire";i:-1;s:4:"tags";a:6:{i:0;s:27:"config:shortcut.set.default";i:1;s:24:"config:system.menu.admin";i:2;s:30:"config:user.role.administrator";i:3;s:30:"config:user.role.authenticated";i:4;s:8:"rendered";i:5;s:6:"user:1";}s:8:"checksum";i:121;}');